---
- hosts: all
  tasks:
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command
      when: ansible_hostname == "k8s-master"

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
      when: ansible_hostname == "k8s-master"

    - name: Copy the join command to server location
      copy: src=join-command dest=/tmp/join-command.sh mode=0777
      when: inventory_hostname in {{ groups['k8s-node'] }}

    - name: Join the node to cluster
      become: yes
      shell: /bin/bash -c /tmp/join-command.sh
      when: inventory_hostname in {{ groups['k8s-node'] }}
