---

apiVersion: apps/v1

kind: Deployment

metadata:
  name: mysql-deployment
  labels:
    app: wordpress
    server: database

spec:
  selector:
    matchLabels:
      app: wordpress

  replicas: 1

  template:
    metadata:
      name: mysql-pod
      labels:
        app: wordpress
        server: database
    spec:
      containers:
        - name: mysql
          image: serogka/my-mysql-wordpress-test:last
          ports:
           - containerPort: 3306

