---
plugin: aws_ec2
regions:
  - eu-central-1

keyed_groups:
  -
    prefix: instance_type
    key: instance_type
  -
    key: placement.region
    prefix: aws_region
  -
    key: tags['Kube-Role']
    prefix: role
  -
    key: state.name
    prefix: state
